apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-grafana
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '75.x.x'
      sourceRef:
        kind: HelmRepository
        name: prometheus-grafana
        namespace: default
      interval: 10m
  values:
    replicaCount: 2